apiVersion: v1
kind: Service
metadata:
  name: logs-otlp
  namespace: otel
spec:
  selector:
    app.kubernetes.io/instance: otel.logs-otlp
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
  type: ClusterIP

